version: 2
updates:
  # Enable version updates for GitHub Actions (main branch)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 10
    reviewers:
      - "vlindersoftware"
    assignees:
      - "vlindersoftware"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for GitHub Actions (release branches)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "release/v*"
    open-pull-requests-limit: 5
    reviewers:
      - "vlindersoftware"
    assignees:
      - "vlindersoftware"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "release-branch"

  # Enable version updates for Docker (main branch)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "vlindersoftware"
    assignees:
      - "vlindersoftware"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for Docker (release branches)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "release/v*"
    open-pull-requests-limit: 3
    reviewers:
      - "vlindersoftware"
    assignees:
      - "vlindersoftware"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "release-branch"
