name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'release/v*'

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Check if PR is ready for merge
        id: ready
        run: |
          echo "Checking if PR is ready for auto-merge..."
          echo "PR author: ${{ github.actor }}"
          echo "PR state: ${{ github.event.pull_request.state }}"
          echo "PR mergeable: ${{ github.event.pull_request.mergeable }}"
          
      - name: Wait for status checks
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "test"
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600
          intervalSeconds: 10

      - name: Auto-merge PR
        if: steps.wait-for-checks.outputs.conclusion == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Auto-merging Dependabot PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} \
            --squash \
            --subject "${{ github.event.pull_request.title }}" \
            --body "Auto-merged dependency update after successful checks"

      - name: Comment on successful merge
        if: steps.wait-for-checks.outputs.conclusion == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Auto-merged by Dependabot** 🤖\n\nAll checks passed successfully. This dependency update has been automatically merged.'
            })

      - name: Comment on failed checks
        if: steps.wait-for-checks.outputs.conclusion != 'success'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Auto-merge blocked** ⚠️\n\nChecks are not passing. Please review the failing checks before merging manually.'
            })
