name: Main Branch Push

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Test and Validate
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
