name: PR Checks

on:
  pull_request:
    branches: [ main, 'release/v*' ]

permissions:
  contents: read
  packages: read
  checks: write

jobs:
  test:
    name: Test and Validate
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

  auto-merge:
    name: Auto-merge Dependabot
    if: github.actor == 'dependabot[bot]'
    needs: test
    uses: ./.github/workflows/auto-merge.yml
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
